baseURL = 'https://austinyhc.github.io/just-austin/'
languageCode = 'en-us'
title = 'Austin: Abstraction, Aperture, Apron'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  showShareButtons = false
  showCodeCopyButtons = true

  [params.profileMode]
    enabled = true
    title = "Austin: Abstraction, Aperture, Apron"
    subtitle = "I am Austin; A System Software Engineer by passion. Data Science Practitioner at heart. Avid reader. Essentialist. Nerd. Newbie Rustacean. Virgo. ♍"
    imageUrl = "/profile.jpg"
    imageWidth = 150
    imageHeight = 150
    buttons = [
      { name = "Browse Blog Posts", url = "/posts/" }
    ]

  [params.homeInfoParams]
    Title = "Austin: Abstraction, Aperture, Apron"
    Content = "I am Austin; A System Software Engineer by passion. Data Science Practitioner at heart. Avid reader. Essentialist. Nerd. Newbie Rustacean. Virgo. ♍"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/austinyhc"
  [[params.socialIcons]]
    name = "x"
    url = "https://twitter.com/austinyht"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/austinyhc/"

[menu]
  [[menu.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 10
